import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/global/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white">

        {/* Page Wrapper */}
        <div className="relative min-h-[200vh]">

          {/* Sticky Navbar */}
          <div className="sticky top-0 z-50 ">
            <Navbar />
          </div>

          {/* Content */}
          <main className="relative z-10 bg-white">
            {children}
          </main>

          {/* Footer Section */}
          <div className="relative overflow-hidden h-screen">
            <Footer />
          </div>

        </div>

      </body>
    </html>
  );
}